CREATE TABLE FACT_VIDEOSTART
(	
    "DATETIME_SKEY" int NOT NULL, 
    "PLATFORM_SKEY" int NOT NULL, 
    "SITE_SKEY" int NOT NULL, 
    "VIDEO_SKEY" int NOT NULL,
    "DB_INSERT_DT"	datetime NOT NULL
);