INSERT INTO STG_DATE
SELECT TO_CHAR(DATETIME,'YYYYMMDDHH24MI')
FROM STG_VIDEOSTART
GROUP BY TO_CHAR(DATETIME,'YYYYMMDDHH24MI')
ORDER BY TO_CHAR(DATETIME,'YYYYMMDDHH24MI');

INSERT INTO STG_PLATFORM
SELECT PLATFORM
FROM STG_VIDEOSTART
GROUP BY PLATFORM
ORDER BY PLATFORM;

INSERT INTO STG_SITE
SELECT SITE
FROM STG_VIDEOSTART
GROUP BY SITE
ORDER BY SITE;

INSERT INTO STG_VIDEO
SELECT VIDEO
FROM STG_VIDEOSTART
GROUP BY VIDEO
ORDER BY VIDEO;

commit;