INSERT INTO DIM_DATE (DATETIME_SKEY)
SELECT f.DATETIME
FROM STG_DATE f
LEFT JOIN DIM_DATE t
ON f.DATETIME = t.DATETIME_SKEY
WHERE t.DATETIME_SKEY IS NULL;

INSERT INTO DIM_PLATFORM (PLATFORM)
SELECT f.PLATFORM
FROM STG_PLATFORM f
LEFT JOIN DIM_PLATFORM t
ON f.PLATFORM = t.PLATFORM
WHERE t.PLATFORM IS NULL;

INSERT INTO DIM_SITE (SITE)
SELECT f.SITE
FROM STG_SITE f
LEFT JOIN DIM_SITE t
ON f.SITE = t.SITE
WHERE t.SITE IS NULL;

INSERT INTO DIM_VIDEO (VIDEO)
SELECT f.VIDEO
FROM STG_VIDEO f
LEFT JOIN DIM_VIDEO t
ON f.VIDEO = t.VIDEO
WHERE t.VIDEO IS NULL;

commit;