INSERT INTO FACT_VIDEOSTART
SELECT DD.DATETIME_SKEY, DP.PLATFORM_SKEY, DS.SITE_SKEY, DV.VIDEO_SKEY, CURRENT_TIMESTAMP
FROM STG_VIDEOSTART VSD
LEFT JOIN DIM_DATE DD ON TO_CHAR(VSD.DATETIME,'YYYYMMDDHH24MI') = DD.DATETIME_SKEY
LEFT JOIN DIM_PLATFORM DP ON VSD.PLATFORM = DP.PLATFORM
LEFT JOIN DIM_SITE DS ON VSD.SITE = DS.SITE
LEFT JOIN DIM_VIDEO DV ON VSD.VIDEO = DV.VIDEO;